### ISSUE TITLE
米窗打开的小窗导致 systemui 崩溃

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [sunshine0523/Mi-FreeForm#20]
已给米窗所有权限。sui/shizuku模式。
米窗内设置保持默认。
在用米窗打开小窗后，systemui必定崩溃。
试图在lsposed里给米窗取消system framework 和system ui的挂钩后使用依旧崩溃。
Android 13 QPR1 类原生。

**Comment by duzhaokun123** [comment]
所以 log 呢

**Comment by JaneValleyhasBtaken** [comment]
你要的log是lsposed内置的log是吗？

**Comment by duzhaokun123** [comment]
可以是  但 logcat 的 更好

**Comment by JaneValleyhasBtaken** [comment]
试图复现这个问题的时候发现它不会再发生了。从提交这个issue到现在发生的改变有：换了内核/启动器，更新了rom（同一个rom只修复了一些bug甚至没有安全更新）。
可能是曾经的其中一环导致了问题，现在不再是了。之后如果有办法复现我再提交log上来

**Comment by JaneValleyhasBtaken** [comment]
暂时关闭这个问题

**Comment by duzhaokun123** [comment]
应该 close as not planned ...

**Comment by JaneValleyhasBtaken** [comment]
嘛...！

**Comment by duzhaokun123** [comment]
> 嘛...！

这个问题没有被解决 因为不能复现

**Comment by JaneValleyhasBtaken** [comment]
好了 改了一下

**Comment by JaneValleyhasBtaken** [comment]
成功复现了 这是lsp里的log
第一次：
[modules_2023-02-21T16_30_54.121564.log](https://github.com/sunshine0523/Mi-FreeForm/files/10789952/modules_2023-02-21T16_30_54.121564.log)
[verbose_2023-02-21T16_30_56.524063.log](https://github.com/sunshine0523/Mi-FreeForm/files/10789953/verbose_2023-02-21T16_30_56.524063.log)


第二次
[modules_2023-02-21T16_36_02.373278.log](https://github.com/sunshine0523/Mi-FreeForm/files/10789955/modules_2023-02-21T16_36_02.373278.log)
[verbose_2023-02-21T16_36_04.062755.log](https://github.com/sunshine0523/Mi-FreeForm/files/10789957/verbose_2023-02-21T16_36_04.062755.log)

**Comment by duzhaokun123** [comment]
米窗混淆了...

用
[app-release.zip](https://github.com/sunshine0523/Mi-FreeForm/files/10790708/app-release.zip)
重试

**Comment by JaneValleyhasBtaken** [comment]
新抓的
[modules_2023-02-23T14_48_17.731597.log](https://github.com/sunshine0523/Mi-FreeForm/files/10810074/modules_2023-02-23T14_48_17.731597.log)

[verbose_2023-02-23T14_48_19.118566.log](https://github.com/sunshine0523/Mi-FreeForm/files/10810075/verbose_2023-02-23T14_48_19.118566.log)

**Comment by JaneValleyhasBtaken** [comment]
之后我用logcat再抓一下

**Comment by duzhaokun123** [comment]
没 系统崩溃的记录
发 logcat 吧

**Comment by JaneValleyhasBtaken** [comment]
有一整个压缩包，我不知道发那个，就只发了跟lsposed管理器log里名字一样的log🥲
logcat的话我之后有空用matlog抓一下

**Comment by duzhaokun123** [comment]
> 有一整个压缩包，我不知道发哪个

为什么不发压缩包

**Comment by JaneValleyhasBtaken** [comment]
好吧，如果你需要的话我发给你
[LSPosed_2023-02-23T14_48_50.103116.zip](https://github.com/sunshine0523/Mi-FreeForm/files/10810165/LSPosed_2023-02-23T14_48_50.103116.zip)

**Comment by duzhaokun123** [comment]
大概什么时间

**Comment by JaneValleyhasBtaken** [comment]
14:44:39 
和
14:48:17
这两个时间点左右

**Comment by duzhaokun123** [comment]
两次 systemui 都是这么炸的
```
02-23 14:44:45.581  6203  6203 E AndroidRuntime: FATAL EXCEPTION: main
02-23 14:44:45.581  6203  6203 E AndroidRuntime: Process: com.android.systemui, PID: 6203
02-23 14:44:45.581  6203  6203 E AndroidRuntime: java.lang.IllegalArgumentException: display must not be null
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at android.app.ContextImpl.createDisplayContext(ContextImpl.java:2664)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:48)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:36)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:712)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-23 14:44:45.581  6203  6203 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by JaneValleyhasBtaken** [comment]
可以为我解答这是什么意思吗？

**Comment by duzhaokun123** [comment]
看上去像有 taost 试图在不存在的 display 上显示导致的

**Comment by JaneValleyhasBtaken** [comment]
所以可能是米窗导致的…？

**Comment by duzhaokun123** [comment]
> 所以可能是米窗导致的…？

是 但不全是

应用用 activity 创建 toast 是很正常的事情 但 virtual display 没有`VIRTUAL_DISPLAY_FLAG_PUBLIC`的 flag 的话

会找不到 display 然后就炸了

米窗没加这个 flag 所以部分应用在小窗中必然导致系统崩溃

**Comment by JaneValleyhasBtaken** [comment]
确实。我尝试了一下其他应用。没有再出现类似的问题了。
