### ISSUE TITLE
the application always crash

### ISSUE THREAD

**Issue by Vannixb** [sunshine0523/Mi-FreeForm#38]
https://bin.kv2.dev/~650fb5dd5de7ed6bfdb95afc

**Comment by sunshine0523** [comment]
Service is not running. You can get log at /data/system/mi_freeform

**Comment by Vannixb** [comment]
> Service is not running. You can get log at /data/system/mi_freeform

[i] Mi-Freeform/ZygoteMain instance MiFreeformUIService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder input not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder input not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder notification not start, wait 1s
[i] Mi-Freeform/MiFreeformUIService add mi_freeform SystemService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146

**Comment by hyhcrh** [comment]
Same problem on Lineage OS 20 a13
Cannot open the app, and /data/system/mi_freeform/log.log shows the same thing

**Comment by 0warning0error** [comment]
same problem on lineageos 20 a13
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: motorola
[Device Model]: motorola edge 20 pro
[Display]: lineage_pstar-userdebug 13 TQ3A.230901.001 90f2d8dd02
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_TW_#Hant
[Process ID]: 9458
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.sunshine.freeform
[Version Name]: 3.0.6-Preview
[Version Code]: 3006
[Target SDK]: 34
[Min SDK]: 27
[Error Type]: JVM
[Crash Time]: 2024-01-10T11:26:28.690
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6703)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by AlirezaParsi** [comment]
I have this problem exactly when i installed shamiko
do you installed shamiko like me?
`[i] Mi-Freeform/ZygoteMain instance MiFreeformUIService: io.sunshine0523.freeform.service.MiFreeformUIService@d83693c
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s
[i] Mi-Freeform/SystemServiceHolder input not start, wait 1s
[i] Mi-Freeform/MiFreeformUIService add mi_freeform SystemService: io.sunshine0523.freeform.service.MiFreeformUIService@d83693c
`
> > Service is not running. You can get log at /data/system/mi_freeform
> 
> [i] Mi-Freeform/ZygoteMain instance MiFreeformUIService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146 [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder input not start, wait 1s [i] Mi-Freeform/SystemServiceHolder input not start, wait 1s [i] Mi-Freeform/SystemServiceHolder notification not start, wait 1s [i] Mi-Freeform/MiFreeformUIService add mi_freeform SystemService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146

**Comment by AlirezaParsi** [comment]
> I have this problem exactly when i installed shamiko do you installed shamiko like me? `[i] Mi-Freeform/ZygoteMain instance MiFreeformUIService: io.sunshine0523.freeform.service.MiFreeformUIService@d83693c [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder input not start, wait 1s [i] Mi-Freeform/MiFreeformUIService add mi_freeform SystemService: io.sunshine0523.freeform.service.MiFreeformUIService@d83693c `
> 
> > > Service is not running. You can get log at /data/system/mi_freeform
> > 
> > 
> > [i] Mi-Freeform/ZygoteMain instance MiFreeformUIService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146 [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder activity not start, wait 1s [i] Mi-Freeform/SystemServiceHolder input not start, wait 1s [i] Mi-Freeform/SystemServiceHolder input not start, wait 1s [i] Mi-Freeform/SystemServiceHolder notification not start, wait 1s [i] Mi-Freeform/MiFreeformUIService add mi_freeform SystemService: io.sunshine0523.freeform.service.MiFreeformUIService@60dd146

Also rom log
https://paste.crdroid.net/mgcub0

**Comment by AlirezaParsi** [comment]
also when i installed mi freeform my emergency and safety syatem app crashing 
system log :
https://paste.crdroid.net/fWzndM
