### ISSUE TITLE
Android 14 QPR2提示“米窗服务未运行”

### ISSUE THREAD

**Issue by crrashh1542** [sunshine0523/Mi-FreeForm#67]
### 运行环境
- 系统：类原生，RisingOS 2.1
- 安卓版本：Android 14 QPR2
- Mi-FreeForm版本：[3.0.6 Preview](https://github.com/sunshine0523/Mi-Freeform/releases/tag/v3.0.6-preview) Zygisk
- Zygisk实现：KernelSU 0.9.4 + Zygisk Next 1.0.5

### 出现状况
刷入后在能正常呼出小窗侧边栏，但是无法进入小窗应用。

https://github.com/sunshine0523/Mi-Freeform/assets/33298711/59a7e034-91d0-4287-ba4e-f36cad554dc3

进入小窗App后，即使已经在LSPosed管理器里启用，仍然提示“米窗服务未运行”
![Screenshot_20240510-230431_Shell](https://github.com/sunshine0523/Mi-Freeform/assets/33298711/0db0e62b-d2e3-4d1a-87d1-f25b1e5cd165)  
![Screenshot_20240510-230521_米窗](https://github.com/sunshine0523/Mi-Freeform/assets/33298711/fda2562a-750a-4d97-93f7-0987576def92)

### 相关日志
米窗应用内日志
```
Maybe Mi-FreeForm can't link mi_freeform service. You can get log at /data/system/mi_freeform/log.log
```

/data/system/mi_freeform/log.log
```
[i] Mi-Freeform/ZygoteMain find display service: com.android.server.display.DisplayManagerService$BinderService@545b9be
[e] Mi-Freeform/ZygoteMain instanceMiFreeformService failed: java.lang.reflect.InvocationTargetException
```

LSPosed框架日志
```
[ 2024-05-10T22:57:59.011     1000:  1989:  1989 I/LSPosed-Bridge  ]   Loading class io.sunshine0523.sidebar.hook.HookWindowManager
[ 2024-05-10T22:58:00.949     1000:  1989:  1989 E/LSPosed-Bridge  ] o.BN.ESxFqb.lhRGn.ip.Y.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.wm.InsetsPolicy$InsetsPolicyAnimationControlListener
	at o.BN.ESxFqb.lhRGn.ip.Y.XposedHelpers.findClass(Unknown Source:12)
	at io.github.lsposed.disableflagsecure.DisableFlagSecure.handleLoadPackage(Unknown Source:138)
	at o.BN.ESxFqb.lhRGn.ip.Y.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at o.BN.ESxFqb.lhRGn.ip.Y.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at o.BN.ESxFqb.lhRGn.ip.Y.callbacks.XCallback.callAll(Unknown Source:26)
	at H0.a(Unknown Source:30)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:123)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:978)
	at com.android.server.SystemServer.main(SystemServer.java:701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)
Caused by: java.lang.ClassNotFoundException: com.android.server.wm.InsetsPolicy$InsetsPolicyAnimationControlListener
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at q.a(Unknown Source:16)
	at o.BN.ESxFqb.lhRGn.ip.Y.XposedHelpers.findClass(Unknown Source:4)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.android.server.wm.InsetsPolicy$InsetsPolicyAnimationControlListener
	... 17 more
```

**Comment by MNDIA** [comment]
QPR2To be fixed +1, it happened to me too

**Comment by cyo57** [comment]
相同环境 但刷入米窗后zygisk next会崩溃

**Comment by Yazed-Hasan** [comment]
same here

**Comment by WhiteXero** [comment]
same

**Comment by kde-yyds** [comment]
same

**Comment by Easorw-Kin** [comment]
me too
