### ISSUE TITLE
Notification Apps has not been Initialised

### ISSUE THREAD

**Issue by mjain234** [sunshine0523/Mi-FreeForm#9]
Been using freeform for a while and never faced this issue before but now facing these days and very frequently.
I have provided you the crash logs but i dont know what makes this app crashes in the background.

[Device Brand]: OPPO
[Device Model]: RMX1801
[Display]: RMX1801EX_11_F.12
[Android Version]: 10
[API Version]: 29
[System Locale]: en_US
[Package Name]: com.sunshine.freeform
[Error Type]: Jvm
[Crash Time]: 2022-10-28T11:23:14.295
[Stack Trace]:
y4.f: lateinit property notificationApps has not been initialized
	at com.sunshine.freeform.service.notification.NotificationService.onNotificationPosted(SourceFile:6)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:346)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2023)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7824)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by sunshine0523** [comment]
The next version maybe fix this bug
